// Builds src/index.ts from the specs present in openapi/.
//
// The visible surface of this package is one factory per service. They are
// generated rather than written out, for the same reason the clients themselves
// are: a service that appears under openapi/ has to arrive complete, and a
// hand-maintained list is where "we added monitoring last week" goes to be
// forgotten.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const services = readdirSync('./openapi')
    .filter((name) => name.endsWith('.yaml'))
    .map((name) => name.replace(/\.yaml$/, ''))
    .sort();

/** iam -> Iam, so the factory reads createIamClient. */
function titleCase(service) {
    return service.charAt(0).toUpperCase() + service.slice(1);
}

// One namespace per service: different services define types with the same name.
const lines = [
    '// Generated by scripts/build-index.mjs. Do not edit.',
    "import { bindClient, createClient } from './http.js';",
    "import type { Bound, ClientOptions } from './http.js';",
    '',
    ...services.map(
        (s) => `import * as ${s}Operations from './generated/${s}/index.js';`,
    ),
    '',
    "export { createClient } from './http.js';",
    "export type { Client, ClientOptions, TokenProvider } from './http.js';",
    '',
    '/* The models, and the operations as free functions for anyone binding a client themselves. */',
    ...services.map((s) => `export * as ${s} from './generated/${s}/index.js';`),
    '',
];

for (const service of services) {
    const name = titleCase(service);

    lines.push(
        `/** Every ${service} operation, bound to one address and one token. */`,
        `export type ${name}Client = Bound<typeof ${service}Operations>;`,
        '',
        '/**',
        ` * A client for ${service}.`,
        ' *',
        ' *     const ' +
            service +
            ' = create' +
            name +
            'Client({ baseURL, getToken });',
        ' *',
        ' * Hold one per address, and — where the token belongs to the request',
        ' * rather than to the process — one per request. There is no',
        ' * process-wide alternative; see `createClient`.',
        ' */',
        `export function create${name}Client(options: ClientOptions): ${name}Client {`,
        `    return bindClient(${service}Operations, createClient(options));`,
        '}',
        '',
    );
}

lines.push(
    '/** Service versions the bundled specs were generated from. */',
    'export const SERVICE_VERSIONS: Record<string, string> = {',
    ...services.map((s) => {
        const version = readFileSync(`./openapi/${s}.version`, 'utf8').trim();
        return `    ${s}: ${JSON.stringify(version)},`;
    }),
    '};',
    '',
);

writeFileSync('./src/index.ts', lines.join('\n'));
console.log(
    `src/index.ts: ${services.length} services -> ${services.join(', ')}`,
);
