// Builds src/index.ts from the specs present in openapi/.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const services = readdirSync('./openapi')
    .filter((name) => name.endsWith('.yaml'))
    .map((name) => name.replace(/\.yaml$/, ''))
    .sort();

// One namespace per service: different services define types with the same name.
const lines = [
    '// Generated by scripts/build-index.mjs. Do not edit.',
    "export { configure, createClient, request, withClient } from './http.js';",
    "export type { Client, ClientOptions, RequestOptions, TokenProvider } from './http.js';",
    '',
    ...services.map((s) => `export * as ${s} from './generated/${s}/index.js';`),
    '',
    '/** Service versions the bundled specs were generated from. */',
    'export const SERVICE_VERSIONS: Record<string, string> = {',
    ...services.map((s) => {
        const version = readFileSync(`./openapi/${s}.version`, 'utf8').trim();
        return `    ${s}: ${JSON.stringify(version)},`;
    }),
    '};',
    '',
];

writeFileSync('./src/index.ts', lines.join('\n'));
console.log(`src/index.ts: ${services.length} services -> ${services.join(', ')}`);
