// Generated by scripts/build-index.mjs. Do not edit.
import { bindClient, createClient } from './http.js';
import type { Bound, ClientOptions } from './http.js';

import * as assistantOperations from './generated/assistant/index.js';
import * as computeOperations from './generated/compute/index.js';
import * as iamOperations from './generated/iam/index.js';
import * as monitoringOperations from './generated/monitoring/index.js';

export { createClient } from './http.js';
export type { Client, ClientOptions, TokenProvider } from './http.js';

/* The models, and the operations as free functions for anyone binding a client themselves. */
export * as assistant from './generated/assistant/index.js';
export * as compute from './generated/compute/index.js';
export * as iam from './generated/iam/index.js';
export * as monitoring from './generated/monitoring/index.js';

/** Every assistant operation, bound to one address and one token. */
export type AssistantClient = Bound<typeof assistantOperations>;

/**
 * A client for assistant.
 *
 *     const assistant = createAssistantClient({ baseURL, getToken });
 *
 * Hold one per address, and — where the token belongs to the request
 * rather than to the process — one per request. There is no
 * process-wide alternative; see `createClient`.
 */
export function createAssistantClient(options: ClientOptions): AssistantClient {
    return bindClient(assistantOperations, createClient(options));
}

/** Every compute operation, bound to one address and one token. */
export type ComputeClient = Bound<typeof computeOperations>;

/**
 * A client for compute.
 *
 *     const compute = createComputeClient({ baseURL, getToken });
 *
 * Hold one per address, and — where the token belongs to the request
 * rather than to the process — one per request. There is no
 * process-wide alternative; see `createClient`.
 */
export function createComputeClient(options: ClientOptions): ComputeClient {
    return bindClient(computeOperations, createClient(options));
}

/** Every iam operation, bound to one address and one token. */
export type IamClient = Bound<typeof iamOperations>;

/**
 * A client for iam.
 *
 *     const iam = createIamClient({ baseURL, getToken });
 *
 * Hold one per address, and — where the token belongs to the request
 * rather than to the process — one per request. There is no
 * process-wide alternative; see `createClient`.
 */
export function createIamClient(options: ClientOptions): IamClient {
    return bindClient(iamOperations, createClient(options));
}

/** Every monitoring operation, bound to one address and one token. */
export type MonitoringClient = Bound<typeof monitoringOperations>;

/**
 * A client for monitoring.
 *
 *     const monitoring = createMonitoringClient({ baseURL, getToken });
 *
 * Hold one per address, and — where the token belongs to the request
 * rather than to the process — one per request. There is no
 * process-wide alternative; see `createClient`.
 */
export function createMonitoringClient(options: ClientOptions): MonitoringClient {
    return bindClient(monitoringOperations, createClient(options));
}

/** Service versions the bundled specs were generated from. */
export const SERVICE_VERSIONS: Record<string, string> = {
    assistant: "v2.1.1",
    compute: "v2.1.1",
    iam: "v0.30.0",
    monitoring: "v9.0.2",
};
